### ISSUE TITLE
GSPen.py errors

### ISSUE THREAD

**Issue by weiweihuanghuang** [schriftgestalt/Glyphs-Scripts#23]
Trying to run 
```
import GSPen
Glyphs.clearLog()

GSPen.test()
```

Gives me these errors:
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "~/Library/Application Support/Glyphs/Scripts/GSPen.py", line 80, in test
    p = GSPen(RGlyph(g))
  File "~/Library/Application Support/Glyphs/Scripts/GSPen.py", line 20, in __init__
    SegmentToPointPen.__init__(self, GSPointPen(r_glyph))
TypeError: __init__() takes exactly 3 arguments (2 given)
```

**Comment by weiweihuanghuang** [comment]
Still trying to use test but get this error.
