### ISSUE TITLE
Make Unicase Font broken

### ISSUE THREAD

**Issue by simoncozens** [schriftgestalt/Glyphs-Scripts#30]
I get this error every time:

```
Start
Lower a
Traceback (most recent call last):
  File "Make Unicase Font.py", line 21, in <module>
    lowerGlyph.leftKerningGroup = upperGlyph.leftKerningGroup
  File "GlyphsApp/__init__.py", line 3876, in <lambda>
  File "GlyphsApp/__init__.py", line 453, in NSStr
ValueError: NSInvalidArgumentException - *** -[NSPlaceholderString initWithString:]: nil argument
End
```

**Comment by schriftgestalt** [comment]
Check if 'upperGlyph.leftKerningGroup' is mit None. I'll add a check.
