### ISSUE TITLE
Not working in Glyphs 2.5.1

### ISSUE THREAD

**Issue by Malou1** [schriftgestalt/Glyphs-Scripts#38]
Remove Layer specific Metrics Keys.py
I get this error : 

```
Start
Traceback (most recent call last):
  File "Remove Layer specific Metrics Keys.py", line 33, in <module>
    remove()
  File "Remove Layer specific Metrics Keys.py", line 20, in remove
    Key = FilterLayerKey(layer.leftMetricsKey())
TypeError: 'NoneType' object is not callable
End
```

**Comment by schriftgestalt** [comment]
Fixed it. Thanks
